common/urls.py
# -*- coding: utf-8 -*-
"""
common urls
"""
from django.conf import settings
from django.urls import path

from common.views import HomeView, home_view

app_name = 'common'

if settings.VIEW_TYPES == 'CBV':
    urlpatterns = [
        path('', HomeView.as_view(), name='home'),
    ]
else:
    urlpatterns = [
        path('', home_view, name='home'),
    ]

gcbv_demo/urls.py
# -*- coding: utf-8 -*-
"""
gcbv_demo URL Configuration
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todo/', include('todo.urls', namespace='todo')),
    path('mage/', admin.site.urls),
    path('', include('common.urls', namespace='common'))
]

todo/urls.py
# -*- coding: utf-8 -*-
"""
Url config for todo app
"""
from django.conf import settings
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from todo.views import CreateTodoListView, DeleteTodoListView, DisplayTodoListView, ListAndFilterTodoListsView, \
    ListTodoListsView, SearchListsView, TodoItemViewSet, UpdateTodoListView, create_todo_list_view, \
    delete_todo_list_view, display_todo_list_view, home_view, list_todo_lists_view, redirect_to_list_todo_lists_view, \
    search_lists_view, update_todo_list_view

app_name = 'todo'

if settings.VIEW_TYPES == 'CBV':
    print('using class-based views')

    urlpatterns = [
        path('show-all-lists/', RedirectView.as_view(pattern_name='todo:list_and_filter_todo_lists'),
             name='show_all_lists'),
        path('list-todo-lists/', ListTodoListsView.as_view(), name='list_todo_lists'),
        path('lists/', ListAndFilterTodoListsView.as_view(), name='list_and_filter_todo_lists'),
        path('create-todo-list/', CreateTodoListView.as_view(), name='create_todo_list'),
        path('display-todo-list/<int:pk>/', DisplayTodoListView.as_view(), name='display_todo_list'),
        path('update-todo-list/<int:pk>/', UpdateTodoListView.as_view(), name='update_todo_list'),
        path('delete-todo-list/<int:pk>/', DeleteTodoListView.as_view(), name='delete_todo_list'),
        path('search-lists/', SearchListsView.as_view(), name='search_lists'),
        path('', TemplateView.as_view(template_name='todo/home.html'), name='home'),
    ]
else:
    print('using function-based views')

    urlpatterns = [
        path('show-all-lists/', redirect_to_list_todo_lists_view, name='show_all_lists'),
        path('list-todo-lists/', list_todo_lists_view, name='list_todo_lists'),
        path('create-todo-list/', create_todo_list_view, name='create_todo_list'),
        path('display-todo-list/<int:pk>/', display_todo_list_view, name='display_todo_list'),
        path('update-todo-list/<int:pk>/', update_todo_list_view, name='update_todo_list'),
        path('delete-todo-list/<int:pk>/', delete_todo_list_view, name='delete_todo_list'),
        path('search-lists/', search_lists_view, name='search_lists'),
        path('', home_view, name='home'),
    ]

# The rest of the urls will just be to round out the functionality so I'm not going to create them as both CBVs and FBVs
router = routers.DefaultRouter()
router.register(r'items', TodoItemViewSet)

urlpatterns.extend([
    path('api/', include((router.urls, 'items'), namespace='items')),
])

common/views.py
# -*- coding: utf-8 -*-
"""
Common Views
"""
from copy import deepcopy
from typing import Any, Callable, Dict, TypeVar

from django.db.models import ForeignKey, QuerySet
from django.forms import Form
from django.http import Http404, HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.decorators import classonlymethod
from django.utils.translation import ugettext_lazy as _
from django.views import View
from django.views.generic import CreateView, ListView, TemplateView
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.edit import FormMixin
from six import iteritems

from common.helpers import my_awesome_decorator


class HomeView(TemplateView):
    """
    Render home page
    """
    template_name = 'common/home.html'

    @classonlymethod
    def as_view(cls, **initkwargs) -> Callable[[HttpRequest, Any, Any], HttpResponse]:
        """
        Wrap function that as_view produces with decorator.
        :param initkwargs: kwargs to pass to view __init__
        :return: function to represent view, wrapped by decorator
        """
        view = super().as_view(**initkwargs)

        return my_awesome_decorator(view)


def home_view(request: HttpRequest) -> HttpResponse:
    """
    Render todo home page
    :param request: user wsgi request
    :return: home page
    """
    return render(request=request, template_name='common/home.html')


class ProcessGetFormMixin(FormMixin):
    """
    Mixin to handle form GET submissions. Based on loosely on ProcessFormView.
    """
    http_method_names = ['get', 'head', 'options']

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """
        Set up form and if data was passed in, validate it, otherwise render page with form.
        :param request: wsgi request
        :return: response for user
        """
        form = self.get_form()

        if request.GET:
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

        return self.render_to_response(self.get_context_data(form=form))

    def get_form_kwargs(self) -> Dict[str, Any]:
        """
        Get kwargs to instantiate form
        :return: form kwargs
        """
        kwargs = super().get_form_kwargs()

        if self.request.GET:
            kwargs['data'] = deepcopy(self.request.GET)

        return kwargs


class GetFormView(TemplateResponseMixin, ProcessGetFormMixin, View):
    """
    View to prepare a form, and either render it or process its submission data.
    """


TForm = TypeVar('TForm', bound=Form)


class FormListView(ProcessGetFormMixin, ListView):
    """
    View to render/process a form and list out model data.
    """
    # boolean indicating if queryset should be retrieved first-time through, i.e. form hasn't been submitted
    retrieve_queryset_first_time: bool = True

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """
        Add form to class variables that are easily accessible
        :param request: wsgi request
        """
        super().setup(request, *args, **kwargs)

        self.form: TForm

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """
        Set up initial object list, which can be filtered later if need be.
        :param request: wsgi request
        :return: template with form, and possibly a queryset
        """
        if self.retrieve_queryset_first_time:
            self.object_list = self.get_queryset()

            self.check_for_empty_queryset()

        return super().get(request, *args, **kwargs)

    def form_valid(self, form: TForm) -> HttpResponse:
        """
        Retrieves/filters the object list upon successful form submission.
        :param form: validated form
        :return: template with form and list of data
        """
        if not self.retrieve_queryset_first_time:
            self.object_list = self.get_queryset()

        self.form = form
        self.object_list = self.filter_queryset()

        # Already checked this in get, but if we have filtered, need to check if the queryset is empty now.
        self.check_for_empty_queryset()

        context = self.get_context_data(form=form)

        return self.render_to_response(context)

    def filter_queryset(self) -> QuerySet:
        """
        Filters queryset based on form data. Really just a hook for children to modify and enable filtering.
        :return: filtered queryset
        """
        return self.object_list

    def check_for_empty_queryset(self) -> None:
        """
        Checks for an empty queryset and raises an error if appropriate (based on set attrs). Basically just re-doing
        what BaseListView does on GET.
        """
        allow_empty = self.get_allow_empty()

        if not allow_empty:
            # When pagination is enabled and object_list is a queryset, it's better to do a cheap query than to load the
            # unpaginated queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list

            if is_empty:
                raise Http404(_(f'Empty list and "{self.__class__.__name__}.allow_empty" is False.'))


# Code below this is in py2, django 1.11. I didn't feel like converting it since it's not good code, and it's
# "understandable" in its current state.


class MultiFormCreateView(CreateView):
    """
    This allows you to handle multiple forms on one page. It can handle forms that each have their own submit button
    and multiple forms being submitted by one button. You just have to define the attributes accordingly.

    The context names of the forms in the template will be the form class name (lowercase). All the forms will
    also be in 'forms' which is a list.

    form_classes needs to be a list of the forms (classes) you want to use.

    initial needs to be a dict, where the key is the form class and the value is a dict mapping field names to initial
    values. Ex: initial = {ForClsOne: {'field_one': 'value_one'}, FormClsTwo: {'state': 'TX}}

    prefix needs to be a dict mapping form classes to prefixes. If one is not provided for a specific form class, it
    defaults to the form class name (lowercase).

    if relative_url needs args or kwargs, you should set it in one of your methods. dispatch, post, form_valid, or a
    custom method are probably best.

    submit_names needs to be a dict mapping form classes to the 'name' of the submit button you want to use on the
    template for that form.

    submit_multiple needs to be a dict mapping the 'name' of the submit button to a list of the form classes whose forms
    would be submitted with that button. Ex: submit_multiple = {'submit_student_info': [BiographicalInfo, ClassInfo]
    """

    form_classes = []  # Required
    initial = {}  # Optional
    prefix = {}  # Optional
    relative_url = None  # Either this or success_url is required.
    submit_names = {}  # Either this one or submit_multiple are required. Both can be used.
    submit_multiple = {}  # Either this one or submit_names are required. Both can be used.

    def __init__(self, *args, **kwargs):
        """
        Sets some self attributes that will be used in the class. Checks to make sure the appropriate attributes have
        been set.
        """
        super(MultiFormCreateView, self).__init__(**kwargs)
        self.submitted_forms = []
        self.not_submitted_forms = []
        self.forms = {}
        self.instances = []
        self.use_post_data = False

        if not self.form_classes or \
            (not isinstance(self.form_classes, list) and not isinstance(self.form_classes, tuple)):
            raise NotImplementedError('form_classes must be a list or tuple.')

        if not self.submit_names and not self.submit_multiple:
            raise NotImplementedError('Either "submit_names" or "submit_multiple" must be used. Both can be used as '
                                      'well')

    def form_invalid(self, *args, **kwargs):
        """
        Super sent form but forms are self.forms now so they don't need to be passed to self.get_context_data.
        :return: Returns an http response with the context data.
        """
        return self.render_to_response(self.get_context_data())

    def form_valid(self, *args, **kwargs):
        """
        Calls save_forms method. Checks to make sure a success_url or relative_url have been provided. Then can redirect
        to the provided url.
        :return: Returns a redirect to the provided url.
        """
        self.save_forms()

        if self.relative_url:
            return redirect(self.relative_url)
        elif self.success_url:
            return redirect(self.get_success_url())
        else:
            raise NotImplementedError('Either a relative_url or a success_url need to be set.')

    def get_context_data(self, **kwargs):
        """
        Adds each form to the context.
        :return: Returns all the kwargs for the template.
        """
        kwargs['forms'] = []
        if self.forms:
            for cls, form in iteritems(self.forms):
                kwargs[cls] = form
                kwargs.get('forms').append(form)
        else:
            for form_cls in self.form_classes:
                form = self.get_form(form_class=form_cls)
                kwargs['{0}'.format(form_cls.__name__.lower())] = form
                kwargs.get('forms').append(form)

        # because we are not declaring a specific form, pulled super's super's (yes that is repeated intentionally) code
        # here to avoid conflicts.
        if self.object:
            kwargs['object'] = self.object

common/templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <title>Todo List</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="https://kit.fontawesome.com/d45a1f31a2.js" crossorigin="anonymous"
          integrity="sha384-tCIa9x35rFwAnPYwDCoqImEiB9Ai31jfzeslK4Q53KZAXSFi24Px912eIpefo9Bj"></script>
</head>

<body class="{% block body_classes %}container-fluid d-flex flex-column flex-grow h-100 px-0{% endblock body_classes %}">

<div id="skip-link">
  <a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>
</div>

<a id="top"></a>

<header class="container-fluid p-0">
  {% block header %}
    {% block nav_bar %}
      <nav class="navbar navbar-expand-lg navbar-light reg-nav-bar py-0 page-content">
        <button class="navbar-toggler align-self-center my-2" type="button" data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav align-self-end">
            {% block main_nav_bar_items %}
              <li class="nav-item reg-nav-item px-3 px-lg-1 py-0">
                {% url 'todo:home' as todo_home_url %}
                <a class="nav-link text-uppercase text-dark {% if request.path_info == todo_home_url %}active{% endif %}"
                   href="{% url 'todo:home' %}">
                  Todo Home Page
                  {% if request.path_info == todo_home_url %}
                    <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
              <li class="nav-item reg-nav-item px-3 px-lg-1 py-0">
                {% url 'todo:list_and_filter_todo_lists' as todo_lists_listing_url %}
                <a class="nav-link text-uppercase text-dark {% if request.path_info == todo_lists_listing_url %}active{% endif %}"
                   href="{{ todo_lists_listing_url }}">
                  Todo Lists Listing Page
                  {% if request.path_info == todo_lists_listing_url %}
                    <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
            {% endblock main_nav_bar_items %}
          </ul>
        </div>
      </nav>
    {% endblock nav_bar %}

    <div class="row m-0">
      <div class="col page-content">
        <h1 id="head" class="mb-3">{% block page_header %}Todo List{% endblock page_header %}</h1>
      </div>
    </div>
  {% endblock header %}
</header>

<main id="content" class="{% block main_classes %}container-fluid flex-grow p-2{% endblock main_classes %}" role="main">
  {% include 'common/messages_with_dismissability.html' %}

  {% block content %}
  {% endblock content %}
</main>

<footer class="container-fluid bg-light pt-5 border-top">
  {% block footer %}
  {% endblock footer %}
</footer>

{% block end_of_body_js %}
{% endblock end_of_body_js %}

</body>
</html>

common/templates/common/home.html
{% extends 'common/base.html' %}

{% block content %}
  <p>
    Place to keep all your todo items!
  </p>
{% endblock content %}

common/templates/common/messages_with_dismissability.html
{% if messages %}
  <div id="messages">
    {% for message in messages %}
      <div
              class="alert {% if message.level_tag == 'error' %}alert-danger{% else %}alert-{{ message.level_tag }}{% endif %}
                        alert-dismissible fade show {{ message.extra_tags }}"
              role="alert">

        {{ message }}

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  </div>
{% endif %}