gcbv_demo/urls.py
# -*- coding: utf-8 -*-
"""
gcbv_demo URL Configuration
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todo/', include('todo.urls', namespace='todo')),
    path('mage/', admin.site.urls),
    path('', include('common.urls', namespace='common'))
]

todo/urls.py
# -*- coding: utf-8 -*-
"""
Url config for todo app
"""
from django.conf import settings
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from rest_framework import routers

from todo.views import CreateTodoListView, DeleteTodoListView, DisplayTodoListView, ListAndFilterTodoListsView, \
    ListTodoListsView, SearchListsView, TodoItemViewSet, UpdateTodoListView, create_todo_list_view, \
    delete_todo_list_view, display_todo_list_view, home_view, list_todo_lists_view, redirect_to_list_todo_lists_view, \
    search_lists_view, update_todo_list_view

app_name = 'todo'

if settings.VIEW_TYPES == 'CBV':
    print('using class-based views')

    urlpatterns = [
        path('show-all-lists/', RedirectView.as_view(pattern_name='todo:list_and_filter_todo_lists'),
             name='show_all_lists'),
        path('list-todo-lists/', ListTodoListsView.as_view(), name='list_todo_lists'),
        path('lists/', ListAndFilterTodoListsView.as_view(), name='list_and_filter_todo_lists'),
        path('create-todo-list/', CreateTodoListView.as_view(), name='create_todo_list'),
        path('display-todo-list/<int:pk>/', DisplayTodoListView.as_view(), name='display_todo_list'),
        path('update-todo-list/<int:pk>/', UpdateTodoListView.as_view(), name='update_todo_list'),
        path('delete-todo-list/<int:pk>/', DeleteTodoListView.as_view(), name='delete_todo_list'),
        path('search-lists/', SearchListsView.as_view(), name='search_lists'),
        path('', TemplateView.as_view(template_name='todo/home.html'), name='home'),
    ]
else:
    print('using function-based views')

    urlpatterns = [
        path('show-all-lists/', redirect_to_list_todo_lists_view, name='show_all_lists'),
        path('list-todo-lists/', list_todo_lists_view, name='list_todo_lists'),
        path('create-todo-list/', create_todo_list_view, name='create_todo_list'),
        path('display-todo-list/<int:pk>/', display_todo_list_view, name='display_todo_list'),
        path('update-todo-list/<int:pk>/', update_todo_list_view, name='update_todo_list'),
        path('delete-todo-list/<int:pk>/', delete_todo_list_view, name='delete_todo_list'),
        path('search-lists/', search_lists_view, name='search_lists'),
        path('', home_view, name='home'),
    ]

# The rest of the urls will just be to round out the functionality so I'm not going to create them as both CBVs and FBVs
router = routers.DefaultRouter()
router.register(r'items', TodoItemViewSet)

urlpatterns.extend([
    path('api/', include((router.urls, 'items'), namespace='items')),
])

todo/models.py
# -*- coding: utf-8 -*-
"""
models for todo app
"""
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _


class TodoListModel(models.Model):
    """
    Model to keep todo lists
    """
    name = models.CharField(verbose_name=_('list name'), max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self) -> str:
        """
        Retrieve url to view list
        :return: list url
        """
        return reverse_lazy('todo:display_todo_list', kwargs={'pk': self.id})

    def __str__(self) -> str:
        return self.name


class TodoItemModel(models.Model):
    """
    Model for todo items
    """
    todo_list = models.ForeignKey(TodoListModel, default=None, on_delete=models.CASCADE)
    text = models.TextField()
    completed = models.BooleanField()

    class Meta:
        ordering = ('id',)
        unique_together = ('todo_list', 'text')

    def save(self, **kwargs) -> 'TodoItemModel':
        """
        Ensure we save TodoListModel for last_edited field
        :param kwargs: kwargs to pass on to regular save
        :return: saved instance
        """
        instance = super().save(**kwargs)

        self.todo_list.save()

        return instance

    def __str__(self) -> str:
        return self.text

todo/forms.py
# -*- coding: utf-8 -*-
"""
Forms for todo app
"""
from django import forms
from django.utils.translation import ugettext_lazy as _

from todo.models import TodoItemModel, TodoListModel


class SearchListsForm(forms.Form):
    """
    Form to search for existing lists.
    """
    name = forms.CharField(label=_('list name'), required=True)


class TodoListForm(forms.ModelForm):
    """
    Form to create and edit todo lists
    """

    class Meta:
        """
        Define modelform options
        """
        model = TodoListModel
        fields = ['name']


class TodoItemForm(forms.ModelForm):
    """
    Form to create and edit todo items
    """

    class Meta:
        """
        define modelform options
        """
        model = TodoItemModel
        fields = ['todo_list', 'text', 'completed']

todo/views.py
# -*- coding: utf-8 -*-
"""
Views for todo app
"""
from copy import deepcopy
from typing import Any, Dict, List, Union

from django.contrib import messages
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseNotAllowed, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from rest_framework import viewsets

from common.views import FormListView, GetFormView
from todo.forms import SearchListsForm, TodoItemForm, TodoListForm
from todo.models import TodoItemModel, TodoListModel
from todo.serializers import TodoItemSerializer


def home_view(request: HttpRequest) -> HttpResponse:
    """
    Render todo home page
    :param request: user wsgi request
    :return: home page
    """
    return render(request=request, template_name='todo/home.html')


class SearchListsView(GetFormView):
    """
    View to search through existing lists
    """
    form_class = SearchListsForm
    template_name = 'todo/search_lists.html'
    http_method_names = ['get', 'options']

    def get_success_url(self) -> str:
        """
        Build out the url we want to redirect to. We'll combine a redirect to list_todo_lists along with the submitted
        query string.
        :return: url that will lead to a view that filters search lists
        """
        return f"{reverse('todo:list_todo_lists')}?{self.request.META.get('QUERY_STRING')}"


def search_lists_view(request: HttpRequest) -> Union[HttpResponse, HttpResponseRedirect]:
    """
    View to search through existing lists
    :param request: wsgi request
    :return: template with form to search through lists, or redirect to view that will filter lists
    """
    if not request.method == 'GET':
        return HttpResponseNotAllowed(['GET'])

    form_kwargs = {}
    if request.GET:
        form_kwargs['data'] = deepcopy(request.GET)

    form = SearchListsForm(**form_kwargs)

    if request.GET and form.is_valid():
        url = f"{reverse('todo:list_todo_lists')}?{request.META.get('QUERY_STRING')}"

        return redirect(url)

    context = {
        'form': form
    }

    return render(request, 'todo/search_lists.html', context)


class ListTodoListsView(ListView):
    """
    View to list TodoLists
    """
    model = TodoListModel
    template_name = 'todo/list_todo_lists.html'

    def get_queryset(self) -> Union[QuerySet, List[TodoListModel]]:
        """
        Filter queryset, if we need to.
        :return: Returns queryset, either full or filtered
        """
        queryset = super().get_queryset()

        if 'name' in self.request.GET:
            queryset = queryset.filter(name__icontains=self.request.GET['name'])

        return queryset


def list_todo_lists_view(request: HttpRequest) -> HttpResponse:
    """
    View to list TodoLists
    :param request: wsgi request
    :return: template with todo lists
    """
    queryset = TodoListModel.objects.all()
    if 'name' in request.GET:
        queryset = queryset.filter(name__icontains=request.GET['name'])

    context = {
        'object_list': queryset
    }
    return render(request, 'todo/list_todo_lists.html', context)


def redirect_to_list_todo_lists_view(request: HttpRequest) -> HttpResponseRedirect:
    """
    Redirects to the new url we want users to use.
    :param request: wsgi request
    :return: redirect to new url
    """
    return redirect(to='todo:list_todo_lists')


class ListAndFilterTodoListsView(FormListView):
    """
    List and possibly filter todo lists
    """
    form_class = SearchListsForm
    model = TodoListModel
    template_name = 'todo/list_and_filter_todo_lists.html'

    def filter_queryset(self) -> QuerySet:
        """
        Filter queryset based on input name
        :return: filtered queryset
        """
        queryset = super().filter_queryset()

        list_name = self.form.cleaned_data.get('name')

        return queryset.filter(name__icontains=list_name)


class CreateTodoListView(CreateView):
    """
    View to create new todo lists
    """
    template_name = 'todo/create_todo_list.html'
    form_class = TodoListForm


def create_todo_list_view(request: HttpRequest) -> Union[HttpResponse, HttpResponseRedirect]:
    """
    View to create new todo lists
    :param request: wsgi request
    :return: template with form to create new list, or redirect to detail page of list
    """
    if request.method == 'GET':
        form = TodoListForm()

        return render(request, 'todo/create_todo_list.html', {'form': form})
    elif request.method == 'POST':
        form = TodoListForm(data=deepcopy(request.POST))

        if form.is_valid():
            todo_list = form.save()

            return redirect(todo_list.get_absolute_url())
        else:
            return render(request, 'todo/create_todo_list.html', {'form': form})


class DisplayTodoListView(DetailView):
    """
    View to show detailed view of todo list
    """
    template_name = 'todo/display_todo_list.html'
    model = TodoListModel
    context_object_name = 'todo_list'

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        """
        Add new item form to context
        :param kwargs: kwargs for template context
        :return: kwargs for template context with form added
        """
        initial = {
            'todo_list': self.kwargs.get('pk')
        }

        kwargs['form'] = TodoItemForm(initial=initial)

        return super().get_context_data(**kwargs)


def display_todo_list_view(request: HttpRequest, pk: int) -> HttpResponse:
    """
    view to show detailed view of todo list
    :param request: wsgi request
    :param pk: pk of todo list
    :return: template with list details
    """
    todo_list = TodoListModel.objects.get(id=pk)

    return render(request, 'todo/display_todo_list.html', {'todo_list': todo_list})


class UpdateTodoListView(UpdateView):
    """
    View to update a todo list
    """
    template_name = 'todo/update_todo_list.html'
    form_class = TodoListForm
    model = TodoListModel
    context_object_name = 'todo_list'


def update_todo_list_view(request: HttpRequest, pk: int) -> Union[HttpResponse, HttpResponseRedirect]:
    """
    View to update a todo list
    :param request: wsgi request
    :param pk: pk of todo list
    :return: template with form to edit todo list, or redirect to details page
    """
    todo_list = TodoListModel.objects.get(id=pk)

    context = {
        'todo_list': todo_list
    }

    if request.method == 'GET':
        context['form'] = TodoListForm(instance=todo_list)

        return render(request, 'todo/update_todo_list.html', context)
    elif request.method == 'POST':
        form = TodoListForm(data=deepcopy(request.POST), instance=todo_list)

        if form.is_valid():
            todo_list = form.save()

            return redirect(todo_list.get_absolute_url())
        else:
            context['form'] = form
            return render(request, 'todo/update_todo_list.html', {'form': form})


class DeleteTodoListView(DeleteView):
    """
    View to delete a todo list
    """
    template_name = 'todo/delete_todo_list.html'
    model = TodoListModel
    context_object_name = 'todo_list'
    success_url = reverse_lazy('todo:list_and_filter_todo_lists')

    def delete(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL. Overriding to add a message.
        :param request: wsgi request
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        success_message = _(f'Successfully deleted todo list: {self.object}')

        self.object.delete()

        messages.success(request=request, message=success_message)

        return redirect(success_url)


def delete_todo_list_view(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    """
    delete a todo list
    :param request: wsgi request
    :param pk: pk of todo list
    :return: redirect to full listing page
    """
    todo_list = TodoListModel.objects.get(id=pk)

    if request.method == 'GET':
        return render(request, 'todo/delete_todo_list.html', {'todo_list': todo_list})
    elif request.method == 'POST':
        success_message = _(f'Successfully deleted todo list: {todo_list}')

        todo_list.delete()

        messages.success(request=request, message=success_message)

        return redirect(reverse_lazy('todo:list_and_filter_todo_lists'))


class TodoItemViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows todo items to be viewed or edited
    """
    queryset = TodoItemModel.objects.all()
    serializer_class = TodoItemSerializer

    def get_queryset(self) -> QuerySet:
        """
        Enable filtering of todo items queryset by todo_list query param.
        :return: filtered queryset, if todo_list is in query params
        """
        queryset = super().get_queryset()

        todo_list = self.request.query_params.get('todo_list', None)

        if todo_list is not None:
            queryset = queryset.filter(todo_list=todo_list)

        return queryset

todo/templates/todo/create_todo_list.html
{% extends 'common/base.html' %}

{% block page_header %}Create Todo List{% endblock page_header %}

{% block content %}
  <form id="id-create-todo-list-form" action="{% url 'todo:create_todo_list' %}" method="post">
    {% csrf_token %}

    {% include 'common/forms/non_field_errors.html' with non_field_errors=form.non_field_errors %}

    <div class="form-group">
      {% include 'common/forms/basic_field.html' with field=form.name %}
    </div>

    <div>
      <button type="submit" form="id-create-todo-list-form" name="create_todo_list"
              class="btn btn-primary mb-1 mr-sm-1">
        Create Todo List
      </button>
    </div>
  </form>
{% endblock content %}

todo/templates/todo/delete_todo_list.html
{% extends 'common/base.html' %}

{% block page_header %}{{ todo_list.name }}{% endblock page_header %}

{% block content %}
  <section id="id-list-info">
    <h2>List Info</h2>
    <dl>
      <dt>Created:</dt>
      <dd>{{ todo_list.created }}</dd>

      <dt>Last Updated:</dt>
      <dd>{{ todo_list.last_updated }}</dd>

      <dt>Number of list items:</dt>
      <dd>{{ todo_list.todoitemmodel_set.count }}</dd>
    </dl>
  </section>
  <section id="id-confirm-delete">
    <p>
      Any items in this list will also get deleted. Are you sure you want to delete this list?
    </p>
    <form id="id-delete-todo-list-form" action="{% url 'todo:delete_todo_list' pk=todo_list.id %}" method="post">
      {% csrf_token %}
      <div>
        <button type="submit" form="id-delete-todo-list-form" name="delete_todo_list"
                class="btn btn-primary mb-1 mr-sm-1">
          Yes, Delete Todo List
        </button>
      </div>
    </form>
    <a href="{% url 'todo:display_todo_list' pk=todo_list.id %}" title="return to list details"
       class="btn btn-secondary mb-1 mr-sm-1">
      No, Take me back to the List Details
    </a>
  </section>
{% endblock content %}

todo/templates/todo/display_todo_list.html
{% extends 'common/base.html' %}

{% load static %}

{% block page_header %}{{ todo_list.name }}{% endblock page_header %}

{% block content %}
  <section id="id-list-info">
    <h2>List Info</h2>
    <dl>
      <dt>Created:</dt>
      <dd>{{ todo_list.created }}</dd>

      <dt>Last Updated:</dt>
      <dd>{{ todo_list.last_updated }}</dd>
    </dl>

    <a href="{% url 'todo:update_todo_list' pk=todo_list.id %}" title="go to page to update todo list"
       class="btn btn-primary mb-1 mr-sm-1">
      Update Todo List
    </a>
    <a href="{% url 'todo:delete_todo_list' pk=todo_list.id %}" title="go to page to delete todo list"
       class="btn btn-secondary mb-1 mr-sm-1">
      Delete Todo List
    </a>
  </section>
  <section id="id-list-items">
    <h2>List Items</h2>
    <div id="app">
      <p v-if="errors.length">
        <b>Please correct the following error(s)</b>
      <div v-for="error in errors">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          [[ error ]]

          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      </p>
      <p v-if="todoItems===null || todoItems.length===0">This list has no items.</p>
      <div class="form-row d-flex mb-3" :class="item.pk"
           v-for="item in todoItems" :key="item.pk">
        <div class="form-group col-auto">
          <label :for=`id-todo-item-text-${item.pk}` class="sr-only">Todo text:</label>

          <input type="text" :id=`id-todo-item-text-${item.pk}` name="text"
                 class="form-control" :placeholder=`${item.text}`
                 v-model="item.text">
        </div>
        <div class="form-group pl-3 pr-2 pt-1">
          <div class="custom-control custom-checkbox custom-control-inline">
            <input :id=`id-todo-item-completed-${item.pk}` type="checkbox"
                   class="custom-control-input todo-item-completed"
                   name="completed"
                   v-model="item.completed"
                   @change="updateCompletion(item)">
            <label :for=`id-todo-item-completed-${item.pk}`
                   class="custom-control-label">Completed?</label>
          </div>
        </div>
        <i class="fa fa-trash pt-2" @click="deleteItem(item)"></i>
      </div>
      <div class="form-row d-flex mb-3">
        <div class="form-group col-auto">
          <label for="id-new-todo-item-text" class="sr-only">Todo text:</label>
          <input type="text" id="id-new-todo-item-text" name="text"
                 class="form-control" placeholder="new todo item text"
                 v-model="newItem.text">
        </div>
        <div class="form-group pl-3 pr-2 pt-1">
          <div class="custom-control custom-checkbox custom-control-inline">
            <input id='id-new-todo-item-completed' type="checkbox"
                   class="custom-control-input todo-item-completed"
                   name="completed"
                   v-model="newItem.completed">
            <label for="id-new-todo-item-completed"
                   class="custom-control-label">Completed?</label>
          </div>
        </div>
        <i class="fa fa-save pt-2" @click="addItem()"></i>
      </div>
    </div>
  </section>
{% endblock content %}

{% block end_of_body_js %}
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script>
    const todoListPk = "{{ todo_list.pk }}";
    const todoItemListApiUrl = "{% url 'todo:items:todoitemmodel-list' %}";
  </script>
  <script src="{% static 'todo/js/manage_items.js' %}"></script>
{% endblock end_of_body_js %}

todo/templates/todo/home.html
{% extends 'common/base.html' %}

{% block content %}
  <p>
    Time to create a list!
  </p>
  <a href="{% url 'todo:create_todo_list' %}" title="go to page to create new todo list">Create new todo list</a>
{% endblock content %}

todo/templates/todo/list_and_filter_todo_lists.html
{% extends 'common/base.html' %}

{% block page_header %}
  Todo Lists
{% endblock page_header %}

{% block content %}
  {% include 'todo/list_search_form.html' %}
  {% include 'todo/list_table.html' %}
{% endblock content %}

todo/templates/todo/list_search_form.html
<form id="id-search-lists-form" method="get">
  {% include 'common/forms/non_field_errors.html' with non_field_errors=form.non_field_errors %}

  <div class="form-group">
    {% include 'common/forms/basic_field.html' with field=form.name %}
  </div>

  <div>
    <button type="submit" form="id-search-lists-form" name="search_lists" class="btn btn-primary mb-1 mr-sm-1">
      Search through lists
    </button>
  </div>
</form>

todo/templates/todo/list_table.html
{% if object_list %}
  <table class="table table-hover mb-0">
    <caption class="sr-only">List of Todo Lists</caption>
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Created</th>
      <th scope="col">Last Updated</th>
    </tr>
    </thead>
    <tbody>
    {% for todo_list in object_list %}
      <tr>
        <td>
          <a href="{% url 'todo:display_todo_list' pk=todo_list.id %}" title="todo list details">
            {{ todo_list.name }}
          </a>
        </td>
        <td>{{ todo_list.created }}</td>
        <td>{{ todo_list.last_updated }}</td>
      </tr>
    {% endfor class_info %}
    </tbody>
  </table>
{% else %}
  <p>
    {% if view.request.GET.name %}
      No todo lists were found with input name: {{ view.request.GET.name }}
    {% else %}
      No todo lists were found.
    {% endif %}
  </p>
{% endif %}  {# if object_list #}

todo/templates/todo/list_todo_lists.html
{% extends 'common/base.html' %}

{% block page_header %}
  Todo Lists
{% endblock page_header %}

{% block content %}
  {% include 'todo/list_table.html' %}
{% endblock content %}

todo/templates/todo/search_lists.html
{% extends 'common/base.html' %}

{% block page_header %}
  Search through Existing Lists
{% endblock page_header %}

{% block content %}
  {% include 'todo/list_search_form.html' %}
{% endblock content %}

todo/templates/todo/update_todo_list.html
{% extends 'common/base.html' %}

{% block page_header %}Update Todo List{% endblock page_header %}

{% block content %}
  <form id="id-update-todo-list-form" action="{% url 'todo:update_todo_list' pk=todo_list.id %}" method="post">
    {% csrf_token %}

    {% include 'common/forms/non_field_errors.html' with non_field_errors=form.non_field_errors %}

    <div class="form-group">
      {% include 'common/forms/basic_field.html' with field=form.name %}
    </div>

    <div>
      <button type="submit" form="id-update-todo-list-form" name="update_todo_list"
              class="btn btn-primary mb-1 mr-sm-1">
        Update Todo List
      </button>
    </div>
  </form>
  <a href="{% url 'todo:display_todo_list' pk=todo_list.id %}" title="go to page to details page"
     class="btn btn-secondary mb-1 mr-sm-1">
    Go Back to Details
  </a>
{% endblock content %}